//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireOneRestAPIFHS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FH_Images
    {
        public int FH_Image_Key { get; set; }
        public int UserId { get; set; }
        public string UserAlias { get; set; }
        public string Image_Location_URL { get; set; }
        public string Image_Location_Folder { get; set; }
        public Nullable<System.DateTime> Image_Date { get; set; }
        public string Image_Description { get; set; }
        public Nullable<int> Image_Size { get; set; }
        public Nullable<int> Image_Width { get; set; }
        public Nullable<int> Image_Height { get; set; }
        public string Image_Dimentions { get; set; }
        public string Image_Type { get; set; }
        public string Image_Rotation { get; set; }
        public Nullable<int> Image_Category_ID { get; set; }
        public Nullable<int> Image_Album_ID { get; set; }
        public string Image_Album_Name { get; set; }
        public string Image_Reference { get; set; }
        public string Image_Poster { get; set; }
        public Nullable<int> Rate1 { get; set; }
    }
}
