//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireOneRestAPIFHS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int UserInfoId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string UserAlias { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<byte> BirthMonth { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public byte[] RowVersion { get; set; }
        public string PhoneNum { get; set; }
        public string ReadPW { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
